server:
  port: 8083

spring:
  application:
    name: account-opening-service

  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: account_db
        format_sql: true

  flyway:
    enabled: true
    schemas: account_db
    locations: classpath:db/migration
    baseline-on-migrate: true

services:
  customer-service:
    url: ${SERVICES_CUSTOMER_SERVICE_URL:http://localhost:8082}
  savings-account-service:
    url: ${SERVICES_SAVINGS_ACCOUNT_SERVICE_URL:http://localhost:8084}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bank.account: DEBUG
    org.springframework.security: INFO
