apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: aos
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: aos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
